#:schema node_modules/wrangler/config-schema.json
name = "wireit-demo-frontend"
main = "src/index.tsx"
compatibility_date = "2024-12-16"
assets = { directory = "./public", binding = "ASSETS" }

services = [
  { binding = "BACKEND_WORKER", service = "wireit-demo-backend" },
]