
#:schema node_modules/wrangler/config-schema.json
name = "wireit-demo-backend"
main = "src/index.ts"
compatibility_date = "2024-12-16"
assets = { directory = "./public", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "todo-db"
database_id = "bb2fd32f-bec3-4878-a874-4c6942c96ded"
